config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'visited_locations#index'

  resources :friends, only: [:index, :destroy] do
    collection do
      get :ranking
    end
  end
  resources :friend_requests, except: [:edit, :show]
  resources :users, only: :index
  resources :visited_locations, only: [:index, :create] do
  	collection do
  		get :all
  	end
  end
  resources :location_reviews, only: [:index, :new, :create]

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :get_friend, only: :destroy

  def index
  	@friends = current_user.friends
    @count = current_user.received_requests.length
  end

  def destroy
    redirect_to :back unless @friend
    current_user.remove_friend(@friend)
    flash[:notice] = "Friend removed"
    redirect_to friends_path
  end

  def ranking
    @rating = current_user.rating
    @friends_rating = current_user.friends_rating
  end

  private

  def get_friend
    @friend = current_user.friends.find_by(id: params[:id])
  end
end

app/views/friends/index.html.erb
<h1 class="header-id">My Friends</h1>

<div class="float-right btn">
	<div>
		<%= link_to "Friend Request(#{@count})", friend_requests_path %>
	</div>
	<div>
		<%= link_to "Add Friends", users_path %>
	</div>
</div>

<table class="table table-hover">
  <thead>
  	<th>Friends</th>
  </thead>
	<% @friends.each do |user| %>
		<tr id="friend_list_<%= user.id %>">
			<td colspan="4"><%= user.name %></td>
			<td colspan="4"><%= link_to "Visited Locations", root_path(user_id: user.id) %></td>
			<td colspan="4"><%= link_to "Reviews", location_reviews_path(user_id: user.id) %></td>
			<td colspan="4"><%= link_to "Unfriend", friend_path(user), method: :delete %></td>
		</tr>
	<% end %>
</table>

app/views/friends/ranking.html.erb
<h1 class="header-id">Contributions</h1>

<div class="float-right btn">
	<span>My Points: <%= @rating.points %></span>
</div>

<table class="table table-hover">
	<% @friends_rating.each do |user| %>
		<thead>
			<th colspan="4">Friends</th>
			<th colspan="4">Points</th>
		</thead>
		<tr>
			<td colspan="4"><%= user.name %></td>
			<td colspan="4"><%= user.points %></td>
		</tr>
	<% end %>
</table>