config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'visited_locations#index'

  resources :friends, only: [:index, :destroy] do
    collection do
      get :ranking
    end
  end
  resources :friend_requests, except: [:edit, :show]
  resources :users, only: :index
  resources :visited_locations, only: [:index, :create] do
  	collection do
  		get :all
  	end
  end
  resources :location_reviews, only: [:index, :new, :create]

end

app/controllers/location_reviews_controller.rb
class LocationReviewsController < ApplicationController

	before_action :set_user, only: :index

	def index
		@location_reviews = @user.reviewed_locations
	end

	def new
		@visited_location = VisitedLocation.find_by_id params[:visited_location_id]
		@user = @visited_location.user
		redirect_to root_path if @user != current_user
		@location_review = LocationReview.new
	end

	def create
		@user = User.find_by_id location_review_params["user_id"]
		@visited_location = VisitedLocation.find_by_id location_review_params[:visited_location_id]
		redirect_to root_path if @user != current_user || @user != @visited_location.user 
		@location_review = LocationReview.new(location_review_params)
		if @location_review.save
			rating_service = RatingService.new(location_review_params, @user)
			rating_service.update_rating_points
			flash[:notice] = "Review successfully saved."
			redirect_to location_reviews_path(user_id: @user.id)
		else
			render 'new'
		end
	end

	private

	def set_user
		@user = User.find_by_id params[:user_id]
		verify_user(@user)
	end

	def location_review_params
    params.require(:location_review).permit(:user_id, :visited_location_id, :rating, :feedback)
  end

end

app/helpers/location_reviews_helper.rb
module LocationReviewsHelper

  def location_reviews_header(user)
  	if user == current_user
  		"My Reviews"
  	else
  		"#{user.name} Reviews"
  	end
  end

end

app/views/location_reviews/index.html.erb
<h1 class="header-id"><%= location_reviews_header(@user) %></h1>

<table class="table table-hover">
  <thead>
  	<th colspan="4">City</th>
  	<th colspan="4">Rating</th>
  	<th colspan="4">Feedback</th>
  </thead>
	<% @location_reviews.each do |lr| %>
		<tr>
			<td colspan="4"><%= lr.city %></td>
			<td colspan="4"><%= lr.rating %></td>
			<td colspan="4"><%= lr.feedback %></td>
			<td colspan="4">
				<% if lr.lr_id.blank? && @user == current_user %>
					<%= link_to "Add Review", new_location_review_path(visited_location_id: lr.id) %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/location_reviews/new.html.erb
<h1 class="header-id"><%= @visited_location.city %> Review</h1>

<%= form_for(@location_review) do |f| %>
  <% if @location_review.errors.any? %>
    <div id="error_explanation">
      <h5>Please correct the following:</h5>

      <ul>
      <% @location_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :visited_location_id, value: @visited_location.id %>
  <div class="field">
    <%= f.label :rating %>
    <%= f.select :rating, [1,2,3,4,5], prompt: 'rate', class: "form-control", id: "title" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :feedback %>
    <%= f.text_area :feedback, rows: 5, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>