config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'visited_locations#index'

  resources :friends, only: [:index, :destroy] do
    collection do
      get :ranking
    end
  end
  resources :friend_requests, except: [:edit, :show]
  resources :users, only: :index
  resources :visited_locations, only: [:index, :create] do
  	collection do
  		get :all
  	end
  end
  resources :location_reviews, only: [:index, :new, :create]

end

app/models/visited_location.rb
class VisitedLocation < ApplicationRecord
  belongs_to :user
  has_one :location_review, dependent: :destroy
end

app/controllers/visited_locations_controller.rb
class VisitedLocationsController < ApplicationController
  
  def index
  	@user = User.find_by_id params[:user_id]
  	verify_user(@user) if @user
  end

  def create
  	VisitedLocation.create({
  		user_id: current_user.id,
  		city: params[:city],
  		latitude: params[:latitude],
  		longitude: params[:longitude]
  	})
  	flash[:notice] = "Location added to your visited location. Please rate the location."
  	redirect_to root_path
  end

  def all
  	user = params[:user_id].present? ? User.find_by_id(params[:user_id]) : current_user
  	verify_user(user)
  	visited_locations = user.visited_locations.select(:latitude, :longitude)
  	friends_visited_locations = params[:user_id].present? ? [] : user.friends_visited_locations
    render json: {
      success: true, 
      visited_locations: visited_locations,
      friends_visited_locations: friends_visited_locations
    }
  end 

end

app/helpers/visited_locations_helper.rb
module VisitedLocationsHelper

	def visited_locations_header(user)
		if user.present? && user == current_user
			"My Visited Locations"
		elsif user.present?
			"#{user.name} Visited Locations"
		else
			"All Visited Locations"
		end
	end

end

app/views/visited_locations/index.html.erb
<h2 class="header-id"><%= visited_locations_header(@user) %></h2>  

<div class="container">
  <div id="map" class="map"></div>
  <div id="popup" class="ol-popup">
    <%= form_tag visited_locations_path, name: 'mark-location', class: 'form' do %>
      
      <%= label_tag "city" %>
      <%= text_field_tag "city", '', class: "form-controll"%>
      <%= button_tag 'Mark location', class: 'mark-btn btn btn-success btn-sm' %>
    <% end %>
    <a href="#" id="popup-closer" class="ol-popup-closer"></a>
    <div id="popup-content"></div>
    <%= hidden_field_tag 'user_id', @user.try(:id) %>
  </div>
</div>