config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'visited_locations#index'

  resources :friends, only: [:index, :destroy] do
    collection do
      get :ranking
    end
  end
  resources :friend_requests, except: [:edit, :show]
  resources :users, only: :index
  resources :visited_locations, only: [:index, :create] do
  	collection do
  		get :all
  	end
  end
  resources :location_reviews, only: [:index, :new, :create]

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse bar">
  <div class="container">
    <%= link_to "TRIP EXPERIENCE SHARING", root_path, id: "logo" %>
  </div>
</header>

app/views/layouts/_side_bar.html.erb
<div id="wrapper">
  <div id="sidebar-wrapper">
    
    <ul class="sidebar-nav">  
      <li>
        <%= link_to "Home", root_path %>   
      </li>
      <li>
        <%= link_to "My Visited Locations", root_path(user_id: current_user.id) %>   
      </li>
      <li>
        <%= link_to "Review My Visits", location_reviews_path(user_id: current_user.id) %>   
      </li>
      <li>
        <%= link_to "Friends", friends_path %> 
      </li>
      <li>
        <%= link_to "Contributions", ranking_friends_path %> 
      </li>
      <li>
        <%= link_to "Edit Profile", edit_user_registration_path(current_user) %>    
      </li>
      <li>
        <%= link_to "Log out",  destroy_user_session_path, method: "delete" %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripExperienceSharing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css" type="text/css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render 'layouts/header' %>
    </div>

    <% if current_user %>
      <div class="side-div">
        <%= render 'layouts/side_bar' %>
      </div>
    <% end %>

    <div class="body-div">
      <div class="row" >
        <div class="col-md-9" >
          <div class="notice alert-success notice-msg">
            <% if notice %>
              <%= notice %>
            <% end %>
          </div>  
          <p class="notice alert-danger alert-msg">
            <% if alert %>  
              <%= alert %>
            <% end %> 
          </p>  
          <%= yield %>
        </div>  
      </div>
    </div> 
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>